from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument, IncludeLaunchDescription, TimerAction
from launch.launch_description_sources import PythonLaunchDescriptionSource
from launch.substitutions import LaunchConfiguration, PathJoinSubstitution
from launch_ros.actions import Node
from launch_ros.substitutions import FindPackageShare


def generate_launch_description():
    """Launch Gazebo and the nonlinear-control demo node.

    The nonlinear controller is expected to publish joint effort commands while
    reading the robot joint states.  The controller implementation itself is
    intentionally kept separate from the robot-description package.

    Expected controller executable:
        package: omron_cobra_s600_control
        executable: nonlinear_controller

    Suggested control law:
        tau = M(q) [qdd_d + Kd(qd_dot-q_dot) + Kp(qd-q)]
              + C(q,q_dot) q_dot + g(q)

    The desired motion should be generated by the controller as a smooth
    quintic point-to-point trajectory (home -> target -> home).
    """

    use_meshes = LaunchConfiguration('use_meshes')
    kp = LaunchConfiguration('kp')
    kd = LaunchConfiguration('kd')
    move_time = LaunchConfiguration('move_time')

    gazebo_launch = IncludeLaunchDescription(
        PythonLaunchDescriptionSource(
            PathJoinSubstitution([
                FindPackageShare('omron_cobra_s600_description'),
                'launch',
                'gazebo.launch.py',
            ])
        ),
        launch_arguments={
            'use_meshes': use_meshes,
        }.items(),
    )

    nonlinear_controller = Node(
        package='omron_cobra_s600_control',
        executable='nonlinear_controller',
        name='nonlinear_controller',
        output='screen',
        parameters=[{
            'use_sim_time': True,
            'kp': kp,
            'kd': kd,
            'move_time': move_time,
        }],
    )

    # Give Gazebo, ros2_control and the joint-state broadcaster time to start.
    delayed_controller = TimerAction(
        period=5.0,
        actions=[nonlinear_controller],
    )

    return LaunchDescription([
        DeclareLaunchArgument(
            'use_meshes',
            default_value='true',
            description='Use STL meshes in Gazebo.',
        ),
        DeclareLaunchArgument(
            'kp',
            default_value='40.0',
            description='Initial proportional gain for the nonlinear controller.',
        ),
        DeclareLaunchArgument(
            'kd',
            default_value='12.0',
            description='Initial derivative gain for the nonlinear controller.',
        ),
        DeclareLaunchArgument(
            'move_time',
            default_value='5.0',
            description='Seconds for one quintic point-to-point motion segment.',
        ),
        gazebo_launch,
        delayed_controller,
    ])
